spring.application.name=medicas

spring.datasource.url=jdbc:oracle:thin:@bdexp1s1fernandoreyes_tp?TNS_ADMIN=/app/wallet
spring.datasource.username=desarrolloFull
spring.datasource.password=ActForm.S1_BDY
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

logging.level.root=INFO

logging.level.citas.medicas=DEBUG

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE